<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
	<IsTestProject>true</IsTestProject>
	<NoWarn>$(NoWarn);WIAOJ_WEBHOOKS_ED25519</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.9.0" />
	  <PackageReference Include="xunit.v3" Version="4.0.0" />
	  <PackageReference Include="xunit.runner.visualstudio" Version="4.0.0" />
  </ItemGroup>
	
  <ItemGroup>
    <ProjectReference Include="..\..\..\src\Webhooks\Wiaoj.Webhooks.Signing.Asymmetric\Wiaoj.Webhooks.Signing.Asymmetric.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>