<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<RootNamespace>Wiaoj.Querying.OpenApi</RootNamespace>
		<AssemblyName>Wiaoj.Querying.OpenApi</AssemblyName>
		<PackageId>Wiaoj.Querying.OpenApi</PackageId>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
		<PackageReadmeFile>README.md</PackageReadmeFile>
	</PropertyGroup>

	<ItemGroup>
		<None Include="README.md" Pack="true" PackagePath="\" />
	</ItemGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.*" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Wiaoj.Querying.AspNetCore\Wiaoj.Querying.AspNetCore.csproj" />
		<ProjectReference Include="..\..\Preconditions\Wiaoj.Preconditions\Wiaoj.Preconditions.csproj" />
	</ItemGroup>

</Project>
