<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	  <RootNamespace>Wiaoj.Compensation</RootNamespace>
	  <AssemblyName>Wiaoj.Compensation</AssemblyName>
	  <PackageId>Wiaoj.Compensation</PackageId>
	  <GenerateDocumentationFile>true</GenerateDocumentationFile>
	  <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
	  <PackageReadmeFile>README.md</PackageReadmeFile>
	  
	  <IsAotCompatible>true</IsAotCompatible>
	  <EnableTrimAnalyzer>true</EnableTrimAnalyzer>
  </PropertyGroup>

  <ItemGroup>
	  <None Include="..\README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Extensions\Wiaoj.Extensions\Wiaoj.Extensions.csproj" />
  </ItemGroup>


</Project>
