<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.9.0" />
	<PackageReference Include="xunit.v3" Version="4.0.0" />
	<PackageReference Include="xunit.runner.visualstudio" Version="4.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\Serialization\Implementations\Wiaoj.Serialization.Memory\Wiaoj.Serialization.Memory.csproj" />
    <ProjectReference Include="..\..\..\src\Webhooks\Wiaoj.Webhooks.Publishing\Wiaoj.Webhooks.Publishing.csproj" />
    <ProjectReference Include="..\..\..\src\Webhooks\Wiaoj.Webhooks.Transports.InMemory\Wiaoj.Webhooks.Transports.InMemory.csproj" />
    <ProjectReference Include="..\..\..\src\Webhooks\Wiaoj.Webhooks\Wiaoj.Webhooks.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>