<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	  <RootNamespace>Wiaoj.RateLimiting</RootNamespace>
	  <AssemblyName>Wiaoj.RateLimiting</AssemblyName>
	  <PackageId>Wiaoj.RateLimiting</PackageId>
	  <GenerateDocumentationFile>true</GenerateDocumentationFile>
	  <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.11" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.11" />
  </ItemGroup>
	
  <ItemGroup>
    <ProjectReference Include="..\..\DistributedCounter\Wiaoj.DistributedCounter.Abstractions\Wiaoj.DistributedCounter.Abstractions.csproj" />
    <ProjectReference Include="..\..\Extensions\Wiaoj.Extensions\Wiaoj.Extensions.csproj" />
    <ProjectReference Include="..\Wiaoj.RateLimiting.Abstractions\Wiaoj.RateLimiting.Abstractions.csproj" />
  </ItemGroup>

</Project>
