namespace Wiaoj.Identifiers.Generators;

/// <summary>Writes the members of one identifier.</summary>
internal static class IdentifierEmitter {
    public static string Emit(IdentifierTarget target) {
        string name = target.Name;
        string access = target.Accessibility;
        string namespaceLine = target.Namespace.Length == 0 ? "" : $"namespace {target.Namespace};";

        return $$"""
// <auto-generated/>
#nullable enable

{{namespaceLine}}

[global::System.CodeDom.Compiler.GeneratedCode("Wiaoj.Identifiers.Generators", "1.0.0")]
[global::System.Diagnostics.DebuggerDisplay("{Prefix,nq}: {Value.Value}")]
[global::System.Text.Json.Serialization.JsonConverter(typeof({{name}}.{{name}}JsonConverter))]
[global::System.ComponentModel.TypeConverter(typeof({{name}}.{{name}}TypeConverter))]
{{access}} readonly partial record struct {{name}}(global::Wiaoj.Primitives.Snowflake.SnowflakeId Value) :
    global::Wiaoj.Identifiers.IIdentifier<{{name}}>,
    global::System.IComparable<{{name}}>,
    global::System.IComparable,
    global::System.ISpanFormattable,
    global::System.IUtf8SpanFormattable,
    global::System.IParsable<{{name}}>,
    global::System.ISpanParsable<{{name}}>,
    global::System.IUtf8SpanParsable<{{name}}>,
    global::System.Numerics.IComparisonOperators<{{name}}, {{name}}, bool> {

    /// <summary>The prefix written before every <see cref="{{name}}"/>.</summary>
    public const string Prefix = "{{target.Prefix}}";

    static string global::Wiaoj.Identifiers.IIdentifier<{{name}}>.Prefix => Prefix;

    /// <summary>The identifier whose value is zero.</summary>
    public static readonly {{name}} Empty = default;

    /// <summary>Gets whether the value is zero.</summary>
    public bool IsEmpty => this.Value.Value == 0;

    /// <summary>Creates a new identifier from the next Snowflake value.</summary>
    public static {{name}} New() => new(global::Wiaoj.Primitives.Snowflake.SnowflakeId.NewId());

    /// <summary>Creates an identifier from its underlying Snowflake value.</summary>
    public static {{name}} From(global::Wiaoj.Primitives.Snowflake.SnowflakeId value) => new(value);

    /// <summary>Returns the identifier as text, written by <see cref="global::Wiaoj.Identifiers.IdCodec.Current"/>.</summary>
    public override string ToString() => global::Wiaoj.Identifiers.IdCodec.Current.Encode(Prefix, this.Value);

    /// <inheritdoc cref="ToString()"/>
    public string ToString(string? format, global::System.IFormatProvider? formatProvider) => this.ToString();

    public bool TryFormat(global::System.Span<char> destination, out int charsWritten, global::System.ReadOnlySpan<char> format, global::System.IFormatProvider? provider) =>
        global::Wiaoj.Identifiers.IdCodec.Current.TryEncode(Prefix, this.Value, destination, out charsWritten);

    public bool TryFormat(global::System.Span<byte> utf8Destination, out int bytesWritten, global::System.ReadOnlySpan<char> format, global::System.IFormatProvider? provider) {
        global::Wiaoj.Identifiers.IdCodec codec = global::Wiaoj.Identifiers.IdCodec.Current;
        global::System.Span<char> chars = stackalloc char[codec.GetMaxEncodedLength(Prefix)];

        // Identifiers are ASCII, so each character is one UTF-8 byte.
        if(!codec.TryEncode(Prefix, this.Value, chars, out int written) || utf8Destination.Length < written) {
            bytesWritten = 0;
            return false;
        }

        for(int i = 0; i < written; i++) {
            utf8Destination[i] = (byte)chars[i];
        }

        bytesWritten = written;
        return true;
    }

    /// <summary>Reads an identifier written by <see cref="global::Wiaoj.Identifiers.IdCodec.Current"/>.</summary>
    /// <exception cref="global::System.FormatException">The text is not a valid <see cref="{{name}}"/>.</exception>
    public static {{name}} Parse(string s) {
        global::System.ArgumentNullException.ThrowIfNull(s);
        return Parse(global::System.MemoryExtensions.AsSpan(s));
    }

    /// <inheritdoc cref="Parse(string)"/>
    public static {{name}} Parse(global::System.ReadOnlySpan<char> s) =>
        TryParse(s, out {{name}} result) ? result : throw new global::System.FormatException("The text is not a valid {{name}}.");

    /// <inheritdoc cref="Parse(string)"/>
    public static {{name}} Parse(global::System.ReadOnlySpan<byte> utf8Text) =>
        TryParse(utf8Text, out {{name}} result) ? result : throw new global::System.FormatException("The text is not a valid {{name}}.");

    /// <summary>Reads an identifier written by <see cref="global::Wiaoj.Identifiers.IdCodec.Current"/>, without throwing.</summary>
    public static bool TryParse([global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)] string? s, out {{name}} result) {
        if(s is null) {
            result = default;
            return false;
        }

        return TryParse(global::System.MemoryExtensions.AsSpan(s), out result);
    }

    /// <inheritdoc cref="TryParse(string, out {{name}})"/>
    public static bool TryParse(global::System.ReadOnlySpan<char> s, out {{name}} result) {
        bool parsed = global::Wiaoj.Identifiers.IdCodec.Current.TryDecode(Prefix, s, out global::Wiaoj.Primitives.Snowflake.SnowflakeId value);
        result = parsed ? new(value) : default;
        return parsed;
    }

    /// <inheritdoc cref="TryParse(string, out {{name}})"/>
    public static bool TryParse(global::System.ReadOnlySpan<byte> utf8Text, out {{name}} result) {
        bool parsed = global::Wiaoj.Identifiers.IdCodec.Current.TryDecode(Prefix, utf8Text, out global::Wiaoj.Primitives.Snowflake.SnowflakeId value);
        result = parsed ? new(value) : default;
        return parsed;
    }

    static {{name}} global::System.IParsable<{{name}}>.Parse(string s, global::System.IFormatProvider? provider) => Parse(s);

    static bool global::System.IParsable<{{name}}>.TryParse([global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)] string? s, global::System.IFormatProvider? provider, out {{name}} result) => TryParse(s, out result);

    static {{name}} global::System.ISpanParsable<{{name}}>.Parse(global::System.ReadOnlySpan<char> s, global::System.IFormatProvider? provider) => Parse(s);

    static bool global::System.ISpanParsable<{{name}}>.TryParse(global::System.ReadOnlySpan<char> s, global::System.IFormatProvider? provider, out {{name}} result) => TryParse(s, out result);

    static {{name}} global::System.IUtf8SpanParsable<{{name}}>.Parse(global::System.ReadOnlySpan<byte> utf8Text, global::System.IFormatProvider? provider) => Parse(utf8Text);

    static bool global::System.IUtf8SpanParsable<{{name}}>.TryParse(global::System.ReadOnlySpan<byte> utf8Text, global::System.IFormatProvider? provider, out {{name}} result) => TryParse(utf8Text, out result);

    /// <summary>Compares by the underlying Snowflake value, which orders identifiers by creation.</summary>
    public int CompareTo({{name}} other) => this.Value.Value.CompareTo(other.Value.Value);

    public int CompareTo(object? obj) => obj switch {
        null => 1,
        {{name}} other => this.CompareTo(other),
        _ => throw new global::System.ArgumentException("The object is not a {{name}}.", nameof(obj))
    };

    public static bool operator <({{name}} left, {{name}} right) => left.CompareTo(right) < 0;

    public static bool operator <=({{name}} left, {{name}} right) => left.CompareTo(right) <= 0;

    public static bool operator >({{name}} left, {{name}} right) => left.CompareTo(right) > 0;

    public static bool operator >=({{name}} left, {{name}} right) => left.CompareTo(right) >= 0;

    /// <summary>Writes <see cref="{{name}}"/> as a JSON string, also as a dictionary key. Reflection-free, for Native AOT.</summary>
    {{access}} sealed class {{name}}JsonConverter : global::System.Text.Json.Serialization.JsonConverter<{{name}}> {
        public override {{name}} Read(ref global::System.Text.Json.Utf8JsonReader reader, global::System.Type typeToConvert, global::System.Text.Json.JsonSerializerOptions options) {
            if(reader.TokenType != global::System.Text.Json.JsonTokenType.String) {
                throw new global::System.Text.Json.JsonException("A {{name}} must be a JSON string.");
            }

            return ReadText(ref reader);
        }

        public override void Write(global::System.Text.Json.Utf8JsonWriter writer, {{name}} value, global::System.Text.Json.JsonSerializerOptions options) {
            writer.WriteStringValue(value.ToString());
        }

        public override {{name}} ReadAsPropertyName(ref global::System.Text.Json.Utf8JsonReader reader, global::System.Type typeToConvert, global::System.Text.Json.JsonSerializerOptions options) {
            return ReadText(ref reader);
        }

        public override void WriteAsPropertyName(global::System.Text.Json.Utf8JsonWriter writer, {{name}} value, global::System.Text.Json.JsonSerializerOptions options) {
            writer.WritePropertyName(value.ToString());
        }

        private static {{name}} ReadText(ref global::System.Text.Json.Utf8JsonReader reader) {
            bool parsed = reader.HasValueSequence || reader.ValueIsEscaped
                ? TryParse(reader.GetString(), out {{name}} result)
                : TryParse(reader.ValueSpan, out result);

            return parsed ? result : throw new global::System.Text.Json.JsonException("The value is not a valid {{name}}.");
        }
    }

    /// <summary>Converts <see cref="{{name}}"/> to and from its text, for configuration binding and model binding.</summary>
    {{access}} sealed class {{name}}TypeConverter : global::System.ComponentModel.TypeConverter {
        public override bool CanConvertFrom(global::System.ComponentModel.ITypeDescriptorContext? context, global::System.Type sourceType) =>
            sourceType == typeof(string) || base.CanConvertFrom(context, sourceType);

        public override bool CanConvertTo(global::System.ComponentModel.ITypeDescriptorContext? context, [global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)] global::System.Type? destinationType) =>
            destinationType == typeof(string) || base.CanConvertTo(context, destinationType);

        public override object? ConvertFrom(global::System.ComponentModel.ITypeDescriptorContext? context, global::System.Globalization.CultureInfo? culture, object value) =>
            value is string text ? Parse(text) : base.ConvertFrom(context, culture, value);

        public override object? ConvertTo(global::System.ComponentModel.ITypeDescriptorContext? context, global::System.Globalization.CultureInfo? culture, object? value, global::System.Type destinationType) =>
            value is {{name}} id && destinationType == typeof(string) ? id.ToString() : base.ConvertTo(context, culture, value, destinationType);
    }
}
""";
    }
}
