<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	  <RootNamespace>Wiaoj.Pagination.AspNetCore</RootNamespace>
	  <AssemblyName>Wiaoj.Pagination.AspNetCore</AssemblyName>
	  <PackageId>Wiaoj.Pagination.AspNetCore</PackageId>
	  <GenerateDocumentationFile>true</GenerateDocumentationFile>
	  <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
	  <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>
	
	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>
	
	<ItemGroup>
		<ProjectReference Include="..\Wiaoj.Pagination\Wiaoj.Pagination.csproj" />
	</ItemGroup>

	<ItemGroup>
		<None Include="README.md" Pack="true" PackagePath="\" />
	</ItemGroup>

</Project>
