<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<RootNamespace>Wiaoj.DistributedCounter</RootNamespace>
		<AssemblyName>Wiaoj.DistributedCounter</AssemblyName>
		<PackageId>Wiaoj.DistributedCounter</PackageId>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
		<PackageReadmeFile>README.md</PackageReadmeFile>
	</PropertyGroup>

	<ItemGroup>
		<None Include="README.md" Pack="true" PackagePath="\" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.2" />
		<PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.2" />
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.2" />
		<PackageReference Include="Microsoft.Extensions.Options" Version="10.0.2" />
		<PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.2" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Wiaoj.DistributedCounter.Abstractions\Wiaoj.DistributedCounter.Abstractions.csproj" />
		<ProjectReference Include="..\..\Extensions\Concurrency\Wiaoj.Concurrency\Wiaoj.Concurrency.csproj" />
		<ProjectReference Include="..\..\ObjectPool\Wiaoj.ObjectPool\Wiaoj.ObjectPool.csproj" />
		<ProjectReference Include="..\..\Extensions\Primitives\Wiaoj.Primitives\Wiaoj.Primitives.csproj" />
	</ItemGroup>

</Project>