<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<RootNamespace>Wiaoj.BloomFilter.Redis</RootNamespace>
		<AssemblyName>Wiaoj.BloomFilter.Redis</AssemblyName>
		<PackageId>Wiaoj.BloomFilter.Redis</PackageId>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
		<PackageReadmeFile>README.md</PackageReadmeFile>
	</PropertyGroup>

	<ItemGroup>
		<None Include="README.md" Pack="true" PackagePath="\" />
	</ItemGroup>

	<ItemGroup>
		<AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
			<_Parameter1>Wiaoj.BloomFilter.Redis.Tests.Unit</_Parameter1>
		</AssemblyAttribute>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="StackExchange.Redis" Version="2.10.1" />
		<PackageReference Include="Microsoft.Extensions.Options" Version="10.0.2" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.2" />
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.2" />
		<PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.2" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Wiaoj.BloomFilter.Abstractions\Wiaoj.BloomFilter.Abstractions.csproj" />
		<ProjectReference Include="..\Wiaoj.BloomFilter\Wiaoj.BloomFilter.csproj" />
		<ProjectReference Include="..\..\Preconditions\Wiaoj.Preconditions\Wiaoj.Preconditions.csproj" />
	</ItemGroup>

</Project>
