<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	  <RootNamespace>Wiaoj.Webhooks.Resilience</RootNamespace>
	  <AssemblyName>Wiaoj.Webhooks.Resilience</AssemblyName>
	  <PackageId>Wiaoj.Webhooks.Resilience</PackageId>
	  <GenerateDocumentationFile>true</GenerateDocumentationFile>
	  <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

	<ItemGroup>
		<None Include="README.md" Pack="true" PackagePath="\" />
	</ItemGroup>
	
  <ItemGroup>
    <ProjectReference Include="..\..\Resilience\Wiaoj.Resilience\Wiaoj.Resilience.csproj" />
    <ProjectReference Include="..\Wiaoj.Webhooks\Wiaoj.Webhooks.csproj" />
  </ItemGroup>
</Project>
